/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d86302f5-d25d-4922-babb-f9aae4388dcd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_y8yBHuXq9",
    "aws_user_pools_web_client_id": "n4jrmv0ilhnleqlsnr9p0tgtn",
    "oauth": {}
};


export default awsmobile;
